const postcss = require('postcss')
const palx    = require('palx')

function colorSchemeCss(baseColor) {
  const colorScheme = palx(baseColor)
  let css           = ''

  for(hue in colorScheme) {
    if(hue != 'base' && hue != 'black') {
      colorScheme[hue].forEach((shade, i) => {
        css += `  --${hue}-${i}: ${shade};\n`
      })

      css += '\n'
    }
  }

  css = `
/* Generated by postcss-color-scheme */
:root {
  --base-color: ${colorScheme.base};
  --black: ${colorScheme.black};
${css}}`

  return css
}

module.exports = postcss.plugin('color-scheme', (options = {}) => {
  return root => {
    root.walkAtRules(rule => {
      if(rule.name == 'color-scheme') {
        rule.replaceWith(colorSchemeCss(rule.params))
      }
    });
  };
});
